version: '3.8'
services:
  postgres_test:
    container_name: postgres_test
    image: postgres:13
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d postgres_test"]
      interval: 5s
      timeout: 5s
      retries: 5

